[tracker]
url = "udp://localhost:6969"
api_url = "http://localhost:1212"
token = "MyAccessToken"
token_valid_seconds = 7257600 # 12 weeks

[net]
port = 3000

[database]
connect_url = "sqlite://data.db?mode=rwc"

[auth]
min_password_length = 6
max_password_length = 64
secret_key = "verstappennumbahwan"

[storage]
upload_path = "./uploads"
